# code/ai/gen_img2img.py
"""
Main entry point for the img2img utility.
Replaces gen_composite_image.py for composite mode.

Usage:
    python gen_img2img.py --mode composite --bg bg.png --characters char1.png char2.png
    python gen_img2img.py --mode composite --bg bg.png --characters char1.png --char-x 0.3
    python gen_img2img.py --mode composite --manifest AssetManifest_draft.json --output-dir out/

    # Inpaint: --mask accepts a file path OR an object name.
    # When given an object name, claude -p locates it and generates both
    # the mask and the inpaint prompt automatically — no --prompt needed.
    python gen_img2img.py --mode inpaint --input img.png --mask "chair"
    python gen_img2img.py --mode inpaint --input img.png --mask "people"
    python gen_img2img.py --mode inpaint --input img.png --mask mask.png --prompt "stone floor"

    # Inpaint engines (--engine):
    #   flux    — FLUX.1-Fill-dev (default).  Creative diffusion fill.  ~6 GB VRAM.
    #   sdxl    — SDXL patch-based inpaint.  Softer, more painterly.  ~5 GB VRAM.
    #   lama    — LaMa texture continuation. Best for backgrounds/floors/walls.  ~0.2 GB.
    #   opencv  — Classical OpenCV (Telea/NS).  Zero GPU, instant.  Good for small objects.
    python gen_img2img.py --mode inpaint --engine lama  --input img.png --mask "chair"
    python gen_img2img.py --mode inpaint --engine opencv --input img.png --mask mask.png --opencv-method ns
"""

import argparse
import json
import logging
import re
import subprocess
import sys
from pathlib import Path

import torch

sys.path.insert(0, str(Path(__file__).parent))

from img2img import config as cfg
from img2img.io_utils import save_image, ensure_dir

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s — %(message)s",
)
log = logging.getLogger("gen_img2img")

# Modes marked SHOULD_NOT_USE are kept for completeness but must be rejected
# by any AI routing layer (e.g. HTTP server) before dispatch.
# Reason is documented inline so the AI server can return an honest explanation.
SHOULD_NOT_USE = {
    "style": (
        "FLUX schnell img2img cannot preserve scene structure. "
        "Low strength (<=0.75) produces no visible style change. "
        "High strength (>=0.78) hallucinates new objects and completely alters scene composition. "
        "Use --mode canny or --mode depth (ControlNet) for structure-preserving style transfer instead."
    ),
}

PIPELINE_MODES = {
    "composite":    "img2img.pipelines.composite",
    "inpaint":      "img2img.pipelines.inpaint",
    "outpaint":     "img2img.pipelines.outpaint",
    "style":        "img2img.pipelines.style_transfer",   # see SHOULD_NOT_USE
    "pose":         "img2img.pipelines.pose_control",
    "depth":        "img2img.pipelines.depth_control",
    "canny":        "img2img.pipelines.canny_control",
    "upscale":      "img2img.pipelines.upscale_diffusion",
    "bg_replace":   "img2img.pipelines.bg_replace",
    "ip_adapter":   "img2img.pipelines.ip_adapter",
    "relight":      "img2img.pipelines.relight",
    "color_grade":  "img2img.pipelines.color_grade",
}


# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

def _validate_args(mode: str, args) -> None:
    _req = {
        "composite":   [("bg",          "--bg"),
                        ("characters",  "--characters")],
        "inpaint":     [("input",       "--input"),
                        ("mask",        "--mask")],
        # --prompt is optional for inpaint: auto-generated by claude when --mask is an object name
        "outpaint":    [("input",       "--input"),
                        ("prompt",      "--prompt")],
        "style":       [("input",       "--input"),
                        ("prompt",      "--prompt")],
        "pose":        [("input",       "--input"),
                        ("prompt",      "--prompt")],
        "depth":       [("input",       "--input"),
                        ("prompt",      "--prompt")],
        "canny":       [("input",       "--input"),
                        ("prompt",      "--prompt")],
        "upscale":     [("input",       "--input")],
        "bg_replace":  [("input",       "--input"),
                        ("bg",          "--bg")],
        "ip_adapter":  [("input",       "--input"),
                        ("style_image", "--style-image"),
                        ("prompt",      "--prompt")],
        "relight":     [("fg",          "--fg"),
                        ("bg",          "--bg")],
        "color_grade": [("input",       "--input"),
                        ("reference",   "--reference")],
    }
    for attr, flag in _req.get(mode, []):
        val = getattr(args, attr, None)
        if not val:
            raise ValueError(f"[{mode}] missing required argument: {flag}")


# ---------------------------------------------------------------------------
# Argument parser
# ---------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="Image-to-image utility (gen_img2img)")
    p.add_argument("--mode", required=True, choices=list(PIPELINE_MODES))

    # --- Inputs ---
    p.add_argument("--input",        help="Input image path")
    p.add_argument("--bg",           help="Background image (composite, bg_replace, relight)")
    p.add_argument("--fg",           help="Foreground image (relight)")
    p.add_argument("--characters",   nargs="+",
                   help="Character RGBA PNGs (composite). Repeat --char-x/--char-y once per character.")
    p.add_argument("--mask",
                   help="Inpaint mask: a .png file path OR an object name (e.g. 'chair', 'people'). "
                        "When an object name is given, claude -p locates it and auto-generates "
                        "both the mask and the inpaint prompt.")
    p.add_argument("--pose-image",   help="Pose reference image (pose)")
    p.add_argument("--style-image",  help="Style reference image (ip_adapter)")
    p.add_argument("--reference",    help="Color reference image (color_grade)")
    p.add_argument("--prompt",       default="", help="Text prompt")

    # --- Per-character positioning (composite mode) ---
    pos = p.add_argument_group("per-character positioning (composite mode)")
    pos.add_argument("--char-x", dest="char_x", type=float, action="append", metavar="X",
                     help="Horizontal anchor 0-1 per character. Repeat once per --characters entry. "
                          "Missing values are auto-spaced.")
    pos.add_argument("--char-y", dest="char_y", type=float, action="append", metavar="Y",
                     help="Vertical anchor for character bottom 0-1 per character. Default: 0.92.")

    # --- Scaling (composite mode) ---
    scale = p.add_argument_group("depth scaling (composite mode)")
    scale.add_argument("--depth-scale",    action="store_true",  dest="depth_scale")
    scale.add_argument("--no-depth-scale", action="store_false", dest="depth_scale")
    scale.add_argument("--fg-scale",  type=float, default=0.70, dest="fg_scale",
                       help="Character size at foreground depth (default: 0.70)")
    scale.add_argument("--bg-scale",  type=float, default=0.15, dest="bg_scale",
                       help="Character size at background depth (default: 0.15)")
    scale.add_argument("--char-scale", type=float, default=None, dest="char_scale",
                       help="Manual fallback scale when depth is disabled")
    scale.add_argument("--blend-strength", type=float, dest="blend_strength",
                       help="SDXL refinement blend strength 0-1 (0 = Pillow only)")
    p.set_defaults(depth_scale=True)

    # --- Output ---
    p.add_argument("--output",     help="Output path (single image)")
    # Accept both --output-dir and --output_dir for server.py compatibility
    p.add_argument("--output-dir", "--output_dir", dest="output_dir",
                   help="Output directory (batch mode)")

    # --- Batch mode ---
    p.add_argument("--manifest",  help="JSON manifest or AssetManifest for batch mode")
    p.add_argument("--asset-id",  dest="asset_id", default=None,
                   help="Process only this asset_id (batch / manifest mode)")

    # --- Inpaint engine ---
    p.add_argument(
        "--engine",
        choices=["flux", "sdxl", "lama", "opencv"],
        default="flux",
        help=(
            "Inpaint engine (--mode inpaint only). "
            "flux=FLUX.1-Fill-dev (creative diffusion, ~6 GB); "
            "sdxl=SDXL patch-based (~5 GB); "
            "lama=LaMa texture continuation — best for backgrounds (~0.2 GB); "
            "opencv=classical Telea/NS, zero GPU. "
            "Default: flux"
        ),
    )
    p.add_argument(
        "--opencv-method",
        dest="opencv_method",
        choices=["telea", "ns"],
        default="telea",
        help="OpenCV inpaint algorithm (--engine opencv only). telea=Fast Marching (default); ns=Navier-Stokes.",
    )
    p.add_argument(
        "--inpaint-radius",
        dest="inpaint_radius",
        type=int,
        default=5,
        help="Pixel radius for OpenCV inpainting (--engine opencv only). Default: 5.",
    )

    # --- Generation params ---
    p.add_argument("--steps",          type=int)
    p.add_argument("--guidance",       type=float)
    p.add_argument("--strength",       type=float)
    p.add_argument("--scale",          type=int,
                   help="Upscale factor (upscale mode): 2 or 4 (default 4)")
    p.add_argument("--direction",      choices=["left", "right", "up", "down", "all"])
    p.add_argument("--pixels",         type=int, help="Pixels to outpaint")
    p.add_argument("--ip-scale",       type=float, dest="ip_scale")
    p.add_argument("--mode-relight",   choices=["local", "api"], dest="mode_relight")
    p.add_argument("--low-threshold",  type=int, dest="low_threshold")
    p.add_argument("--high-threshold", type=int, dest="high_threshold")
    p.add_argument("--seed",           type=int)
    p.add_argument("--device",         default=cfg.DEVICE)
    p.add_argument("--no-fp16",        action="store_true", dest="no_fp16",
                   help="Disable FP16 (use FP32). Slower but useful for debugging.")
    p.add_argument("--verbose",        action="store_true")

    # --- Auto-mask options (inpaint mode, object-name --mask) ---
    mask_grp = p.add_argument_group("auto-mask (inpaint, when --mask is an object name)")
    mask_grp.add_argument("--claude-bin",   dest="claude_bin",   default="claude",
                          help="Path to claude CLI binary (default: 'claude')")
    mask_grp.add_argument("--mask-padding", dest="mask_padding", type=int, default=20,
                          help="Pixels to expand bounding box on each side (default: 60). "
                               "Use 100-200 for large objects with prominent bases or legs "
                               "where Claude's bbox may underestimate the full extent.")
    mask_grp.add_argument("--no-grabcut",   dest="no_grabcut",   action="store_true",
                          help="Disable GrabCut shape refinement (fall back to plain rect mask)")
    mask_grp.add_argument("--sam-refine",   dest="sam_refine",   action="store_true",
                          help="Refine rect mask to pixel edges using SAM instead of GrabCut (~1 GB VRAM)")
    mask_grp.add_argument("--max-retries",   dest="max_retries",    type=int, default=3,
                          help="Max auto-retry attempts when claude -p reports the object is "
                               "still visible after inpaint (default: 3, 0 = no verification)")
    mask_grp.add_argument("--sam-checkpoint", dest="sam_checkpoint",
                          default=str(Path.home() / ".cache" / "sam" / "sam_vit_b_01ec64.pth"),
                          help="SAM weights path (required when --sam-refine is set)")
    return p


# ---------------------------------------------------------------------------
# Auto-mask: resolve --mask object name → mask PNG + inpaint prompt
# ---------------------------------------------------------------------------

_CLAUDE_MASK_PROMPT = (
    "Look at this image: {image_path}\n\n"
    "I want to completely erase EVERY instance of the {object} from this image using AI inpainting.\n"
    "Return ONLY a single line of JSON with no explanation:\n"
    '{{"instances":[{{"x1":<float>,"y1":<float>,"x2":<float>,"y2":<float>}},...], "prompt":"<string>"}}\n'
    "Where:\n"
    "  instances = list of bounding boxes for EVERY visible {object}, each as fractions 0.0-1.0\n"
    "              of the image width/height (x1,y1=top-left, x2,y2=bottom-right)\n"
    "  prompt    = a detailed description of what should appear in place of all erased {object}s.\n"
    "              Be specific: describe the exact background surface (floor, wall, stone, etc.) "
    "that would be visible. Explicitly state there is NO {object} present.\n"
    "If no {object} is visible in the image, return: {{}}"
)


def _extract_first_json(text: str) -> dict | None:
    """Extract and parse the first JSON object from text, handling nested braces."""
    start = text.find('{')
    if start == -1:
        return None
    depth = 0
    for i, ch in enumerate(text[start:], start):
        if ch == '{':
            depth += 1
        elif ch == '}':
            depth -= 1
            if depth == 0:
                try:
                    return json.loads(text[start:i + 1])
                except json.JSONDecodeError:
                    return None
    return None


def _extract_last_json(text: str) -> dict | None:
    """Extract and parse the LAST JSON object from text.
    Claude sometimes emits two JSON blocks (second-guess pattern) — the last one is more reliable."""
    last = None
    pos = 0
    while True:
        start = text.find('{', pos)
        if start == -1:
            break
        depth = 0
        for i, ch in enumerate(text[start:], start):
            if ch == '{':
                depth += 1
            elif ch == '}':
                depth -= 1
                if depth == 0:
                    try:
                        candidate = json.loads(text[start:i + 1])
                        last = candidate
                    except json.JSONDecodeError:
                        pass
                    pos = i + 1
                    break
        else:
            break
    return last


def resolve_mask_and_prompt(args) -> None:
    """
    If args.mask is an existing file path, do nothing.
    If args.mask is an object description (e.g. 'chair', 'people'):
      1. Call claude -p to get bounding box + inpaint prompt from the image.
      2. Generate a white rect mask PNG next to the input image.
      3. Optionally refine with SAM (--sam-refine).
      4. Set args.mask  = path to generated mask PNG.
      5. Set args.prompt = Claude's suggested prompt (if not already set by user).
    """
    if not args.mask:
        return
    if Path(args.mask).exists():
        log.info(f"[mask] Using existing mask file: {args.mask}")
        return

    # --mask is an object name — auto-generate mask via claude -p
    object_name = args.mask
    image_path  = Path(args.input)
    log.info(f"[mask] Auto-generating mask for '{object_name}' in {image_path.name}...")

    prompt = _CLAUDE_MASK_PROMPT.format(
        image_path=str(image_path.resolve()),
        object=object_name,
    )

    try:
        result = subprocess.run(
            [getattr(args, "claude_bin", "claude"), "-p", prompt],
            capture_output=True, text=True, timeout=60,
        )
    except FileNotFoundError:
        log.error("claude CLI not found. Install Claude Code and ensure it is on PATH.")
        sys.exit(1)
    except subprocess.TimeoutExpired:
        log.error("claude -p timed out after 60s.")
        sys.exit(1)

    if result.returncode != 0:
        log.error(f"claude -p exited {result.returncode}: {result.stderr.strip()}")
        sys.exit(1)

    stdout = result.stdout.strip()
    log.info(f"[mask] Claude response: {stdout}")

    data = _extract_first_json(stdout)
    if data is None:
        log.error(f"No valid JSON found in claude response: {stdout}")
        sys.exit(1)

    # Support both legacy single-bbox {x1,y1,x2,y2,...} and new {instances:[...], prompt:...}
    instances = data.get("instances")
    if instances is None:
        # legacy format: treat the whole dict as one bbox
        required = {"x1", "y1", "x2", "y2"}
        if not required.issubset(data.keys()):
            log.error(f"Incomplete bbox in response: {data}")
            sys.exit(1)
        instances = [{k: data[k] for k in required}]

    if not instances:
        log.error(f"Claude could not find '{object_name}' in the image.")
        sys.exit(1)

    # Clamp all bboxes to 0-1
    bboxes = []
    for raw in instances:
        try:
            bboxes.append({k: max(0.0, min(1.0, float(raw[k]))) for k in ("x1","y1","x2","y2")})
        except (KeyError, TypeError, ValueError) as e:
            log.warning(f"[mask] Skipping malformed bbox {raw}: {e}")
    if not bboxes:
        log.error("No valid bounding boxes found.")
        sys.exit(1)

    log.info(f"[mask] {len(bboxes)} instance(s) found")
    for i, b in enumerate(bboxes):
        log.info(f"  [{i}] x1={b['x1']:.3f} y1={b['y1']:.3f} x2={b['x2']:.3f} y2={b['y2']:.3f}")

    # Generate mask — union of all instance rects
    from PIL import Image as PILImage, ImageDraw
    with PILImage.open(str(image_path)) as img:
        img_w, img_h = img.size

    padding = getattr(args, "mask_padding", 20)
    mask_img = PILImage.new("L", (img_w, img_h), 0)
    draw = ImageDraw.Draw(mask_img)
    for bbox in bboxes:
        x1 = max(0,     int(bbox["x1"] * img_w) - padding)
        y1 = max(0,     int(bbox["y1"] * img_h) - padding)
        x2 = min(img_w, int(bbox["x2"] * img_w) + padding)
        y2 = min(img_h, int(bbox["y2"] * img_h) + padding)
        draw.rectangle([x1, y1, x2, y2], fill=255)
        log.info(f"[mask] Rect: ({x1},{y1})→({x2},{y2})  {x2-x1}x{y2-y1}px")

    # Mask refinement: GrabCut (default) → SAM (opt-in) → rect fallback
    if getattr(args, "sam_refine", False):
        mask_img = _refine_with_sam(image_path, bboxes, mask_img,
                                    getattr(args, "sam_checkpoint", ""),
                                    padding=padding)
    elif not getattr(args, "no_grabcut", False):
        mask_img = _refine_with_grabcut(image_path, bboxes, mask_img, padding=padding)

    # Save mask next to input image
    safe_obj  = object_name.replace(" ", "_")
    mask_path = image_path.parent / f"{image_path.stem}_mask_{safe_obj}.png"
    mask_img.save(str(mask_path))
    log.info(f"[mask] Saved → {mask_path}")

    # Patch args
    args.mask = str(mask_path)
    if not args.prompt and "prompt" in data:
        args.prompt = data["prompt"]
        log.info(f"[mask] Auto-prompt: {args.prompt}")



def _refine_with_grabcut(image_path: Path, bboxes: list,
                         fallback: "PILImage.Image",
                         padding: int = 0) -> "PILImage.Image":
    """
    Refine a rect mask to object shape using GrabCut (cv2).
    Runs on CPU in <1s, zero new dependencies.
    Falls back to the rect mask if GrabCut produces a suspiciously small result
    (< 30% of the rect area — typical of low-contrast or failed segmentation).
    """
    import cv2
    import numpy as np
    from PIL import Image as PILImage

    img_np = np.array(PILImage.open(str(image_path)).convert("RGB"))
    H, W   = img_np.shape[:2]

    union = np.zeros((H, W), dtype=np.uint8)
    for bbox in bboxes:
        x1 = max(0,  int(bbox["x1"] * W) - padding)
        y1 = max(0,  int(bbox["y1"] * H) - padding)
        x2 = min(W,  int(bbox["x2"] * W) + padding)
        y2 = min(H,  int(bbox["y2"] * H) + padding)
        rect_w, rect_h = x2 - x1, y2 - y1
        if rect_w < 4 or rect_h < 4:
            union[y1:y2, x1:x2] = 1
            continue

        gc_mask  = np.zeros((H, W), np.uint8)
        bgd_mdl  = np.zeros((1, 65), np.float64)
        fgd_mdl  = np.zeros((1, 65), np.float64)
        try:
            cv2.grabCut(img_np, gc_mask, (x1, y1, rect_w, rect_h),
                        bgd_mdl, fgd_mdl, 5, cv2.GC_INIT_WITH_RECT)
        except cv2.error as e:
            log.warning(f"[GrabCut] Failed ({e}) — using rect mask for this instance")
            union[y1:y2, x1:x2] = 1
            continue

        fg = np.where((gc_mask == cv2.GC_FGD) | (gc_mask == cv2.GC_PR_FGD), 1, 0).astype(np.uint8)

        # Sanity check: GrabCut sometimes returns near-empty masks on low-contrast scenes
        rect_area = rect_w * rect_h
        fg_area   = int(fg.sum())
        coverage  = fg_area / max(rect_area, 1)
        log.info(f"[GrabCut] bbox=({x1},{y1})→({x2},{y2})  fg={fg_area}px  coverage={coverage:.1%}")

        if coverage < 0.10:
            log.warning(f"[GrabCut] Coverage {coverage:.1%} too low — falling back to rect for this instance")
            union[y1:y2, x1:x2] = 1
        else:
            union = np.clip(union + fg, 0, 1)

    return PILImage.fromarray((union * 255).astype(np.uint8), mode="L")


def _refine_with_sam(image_path: Path, bboxes: list,
                     fallback: "PILImage.Image", checkpoint: str,
                     padding: int = 0) -> "PILImage.Image":
    """
    Run SAM on every bbox instance and return the union mask (white = object).
    bboxes: list of dicts with normalised x1/y1/x2/y2 keys.
    padding: pixels to dilate the SAM mask — captures thin legs/edges and
             grows on retries so the mask expands meaningfully.
    """
    try:
        import torch, numpy as np
        import cv2
        from segment_anything import sam_model_registry, SamPredictor
        from PIL import Image as PILImage
    except ImportError:
        log.warning("segment-anything not installed — using rect mask. "
                    "pip install segment-anything torch torchvision")
        return fallback

    ckpt = Path(checkpoint)
    if not ckpt.exists():
        log.warning(f"SAM checkpoint not found: {ckpt} — using rect mask.")
        return fallback

    # Infer model type from checkpoint filename (vit_h / vit_l / vit_b)
    name = ckpt.stem.lower()
    if "vit_h" in name:
        model_type = "vit_h"
    elif "vit_l" in name:
        model_type = "vit_l"
    else:
        model_type = "vit_b"

    device = "cuda" if torch.cuda.is_available() else "cpu"
    log.info(f"[SAM] Loading {model_type} on {device}...")
    sam  = sam_model_registry[model_type](checkpoint=str(ckpt))
    sam.to(device)
    pred = SamPredictor(sam)

    img_np = np.array(PILImage.open(str(image_path)).convert("RGB"))
    h, w   = img_np.shape[:2]
    pred.set_image(img_np)

    union = np.zeros((h, w), dtype=bool)
    for bbox in bboxes:
        cx  = int(((bbox["x1"] + bbox["x2"]) / 2) * w)
        cy  = int(((bbox["y1"] + bbox["y2"]) / 2) * h)
        bx1 = int(bbox["x1"] * w)
        by1 = int(bbox["y1"] * h)
        bx2 = int(bbox["x2"] * w)
        by2 = int(bbox["y2"] * h)

        masks, scores, _ = pred.predict(
            point_coords=np.array([[cx, cy]]),
            point_labels=np.array([1]),
            box=np.array([bx1, by1, bx2, by2]),
            multimask_output=True,
        )
        best = masks[int(np.argmax(scores))]
        log.info(f"[SAM] bbox=({bx1},{by1})→({bx2},{by2})  score={scores.max():.3f}  coverage={best.sum()}px")
        union |= best

    del sam, pred
    if device == "cuda":
        torch.cuda.empty_cache()

    # Dilate by padding — covers thin elements (legs, edges) and grows on retries
    if padding > 0:
        k = padding * 2 + 1
        kernel = np.ones((k, k), np.uint8)
        union  = cv2.dilate(union.astype(np.uint8), kernel).astype(bool)
        log.info(f"[SAM] After dilation (+{padding}px): coverage={union.sum()}px")

    return PILImage.fromarray((union * 255).astype("uint8"), mode="L")


# ---------------------------------------------------------------------------
# Model loading
# ---------------------------------------------------------------------------

def load_pipe_for_mode(mode: str, args):
    from img2img.model_loader import (
        load_flux_img2img, load_flux_fill, load_flux_controlnet,
        load_flux_redux_prior, load_flux_dev_img2img,
        load_sd_upscaler, load_depth_model,
        load_sdxl_inpaint, load_lama,
    )
    no_fp16 = getattr(args, "no_fp16", False)

    if mode == "composite":
        pipe = {"depth": load_depth_model() if args.depth_scale else None}
        if getattr(args, "blend_strength", None) and args.blend_strength > 0.0:
            pipe["flux"] = load_flux_img2img()
        return pipe

    elif mode == "inpaint":
        engine = getattr(args, "engine", "flux")
        if engine == "lama":
            return load_lama()
        elif engine == "sdxl":
            return load_sdxl_inpaint(no_fp16)
        elif engine == "opencv":
            return None          # OpenCV needs no model
        else:                    # "flux" (default)
            return load_flux_fill()

    elif mode == "outpaint":
        return load_flux_fill()

    elif mode == "style":
        return load_flux_img2img()

    elif mode == "pose":
        return load_flux_controlnet(cfg.MODEL_IDS["flux_controlnet_pose"])

    elif mode == "depth":
        return {"flux_controlnet": load_flux_controlnet(cfg.MODEL_IDS["flux_controlnet_depth"]),
                "depth":           load_depth_model()}

    elif mode == "canny":
        return load_flux_controlnet(cfg.MODEL_IDS["flux_controlnet_canny"])

    elif mode == "upscale":
        return load_sd_upscaler(no_fp16)

    elif mode == "bg_replace":
        pipe = {}
        if getattr(args, "blend_strength", None) and args.blend_strength > 0.0:
            pipe["flux"] = load_flux_img2img()
        return pipe

    elif mode == "ip_adapter":
        return {"prior": load_flux_redux_prior(), "flux": load_flux_dev_img2img()}

    elif mode in ("relight", "color_grade"):
        return None

    raise ValueError(f"Unknown mode: {mode}")


def unload_pipe(pipe) -> None:
    from img2img.model_loader import unload_model
    if isinstance(pipe, dict):
        for v in pipe.values():
            unload_model(v)
    else:
        unload_model(pipe)


# ---------------------------------------------------------------------------
# Single run
# ---------------------------------------------------------------------------

_INPAINT_ENGINE_MODULE = {
    "flux":   "img2img.pipelines.inpaint_flux",
    "sdxl":   "img2img.pipelines.inpaint",
    "lama":   "img2img.pipelines.inpaint_lama",
    "opencv": "img2img.pipelines.inpaint_opencv",
}


def run_single(mode: str, pipe, args) -> None:
    import importlib
    module_path = PIPELINE_MODES[mode]
    if mode == "inpaint":
        engine      = getattr(args, "engine", "flux")
        module_path = _INPAINT_ENGINE_MODULE.get(engine, "img2img.pipelines.inpaint_flux")
        log.info(f"[inpaint] engine={engine}")
    module = importlib.import_module(module_path)

    if args.seed is not None:
        torch.manual_seed(args.seed)

    result  = module.run(pipe, cfg, args)
    out_path = args.output or _default_output(args, mode)
    save_image(result, out_path)
    log.info(f"[{mode}] Done → {out_path}")


def _default_output(args, mode: str) -> str:
    src     = getattr(args, "input", None) or getattr(args, "bg", "output")
    stem    = Path(src).stem
    out_dir = cfg.OUTPUT_DIRS.get(mode, "assets/img2img")
    return str(Path(out_dir) / f"{stem}_{mode}.png")


# ---------------------------------------------------------------------------
# AssetManifest → composite job list
# ---------------------------------------------------------------------------

def _load_asset_manifest_jobs(manifest: dict, out_dir: str,
                               asset_id_filter: str | None) -> list[dict]:
    """
    Convert an AssetManifest (character_packs + backgrounds) into a list of
    composite job dicts compatible with run_batch().
    Mirrors gen_composite_image.py's load_from_manifest() logic exactly.
    """
    bg_ids = [bg["asset_id"] for bg in manifest.get("backgrounds", [])]
    jobs   = []

    for char in manifest.get("character_packs", []):
        char_id   = char["asset_id"]
        char_file = str(Path(out_dir) / f"char-{char_id}-v1-rgba.png")
        ai_prompt = char.get("ai_prompt", "").lower()

        matched_bg = None
        for bg_id in bg_ids:
            keywords = bg_id.replace("bg-", "").split("-")
            if any(kw in ai_prompt for kw in keywords if len(kw) > 4):
                matched_bg = bg_id
                break
        if matched_bg is None and bg_ids:
            matched_bg = bg_ids[0]
        if matched_bg is None:
            continue

        asset_id = f"comp-{char_id}-{matched_bg.replace('bg-', '')}-v1"
        if asset_id_filter and asset_id != asset_id_filter:
            continue

        jobs.append({
            "item_id":    asset_id,
            "bg":         str(Path(out_dir) / f"{matched_bg}-v1.png"),
            "characters": [char_file],
            "char_x":     [0.5],
            "char_y":     [0.92],
        })

    return jobs


# ---------------------------------------------------------------------------
# Batch run
# ---------------------------------------------------------------------------

def run_batch(mode: str, pipe, args) -> None:
    with open(args.manifest, encoding="utf-8") as f:
        data = json.load(f)

    out_dir = ensure_dir(args.output_dir or cfg.OUTPUT_DIRS.get(mode, "out"))

    # Detect AssetManifest vs simple item list
    if isinstance(data, dict) and "character_packs" in data:
        if mode != "composite":
            log.warning(
                "AssetManifest passed but mode=%s — only 'composite' mode supports "
                "AssetManifest auto-pairing. Wrap your items in a JSON array instead.", mode
            )
            return
        items = _load_asset_manifest_jobs(data, str(out_dir),
                                          getattr(args, "asset_id", None))
        log.info(f"AssetManifest → {len(items)} composite job(s)")
    else:
        items = data if isinstance(data, list) else [data]

    log.info(f"Batch: {len(items)} item(s), mode={mode}, output={out_dir}")

    for idx, item in enumerate(items):
        item_id = item.get("item_id") or f"item_{idx:04d}"
        try:
            for k, v in item.items():
                if k != "item_id":
                    setattr(args, k, v)
            args.output = str(out_dir / f"{item_id}.png")
            run_single(mode, pipe, args)
        except Exception as e:
            log.error(f"[{item_id}] Failed: {e}", exc_info=True)

    log.info(f"Batch complete: {len(items)} item(s) processed.")


# ---------------------------------------------------------------------------
# Inpaint verification
# ---------------------------------------------------------------------------

_CLAUDE_VERIFY_PROMPT = (
    "Look at this image: {image_path}\n\n"
    "An AI inpainting tool tried to erase the {object} from this image.\n"
    "Check carefully for ANY part of the {object} still present: the full body, "
    "legs, base, feet, arms, back, seat, or any partial remains — even a single leg "
    "or a small fragment counts as still_present=true.\n"
    "Only count real 3D physical objects, NOT wall paintings, murals, or artwork.\n"
    "Return ONLY a single line of JSON with no explanation:\n"
    '{{"still_present": <true|false>, "confidence": <0.0-1.0>, '
    '"padding_increase": <extra pixels to add to mask_padding to cover the remaining part, 0 if not present>, '
    '"reason": "<one short sentence describing exactly what part is still visible or why it is gone>"}}\n'
    "If still_present=true, set padding_increase large enough to cover the remaining part "
    "(e.g. if only legs remain outside current mask, 100-200px is typical)."
)


def verify_inpaint(output_path: str, object_name: str, claude_bin: str) -> dict:
    """
    Call claude -p to check whether the object is still visible in the output image.
    Returns a dict with keys: still_present, confidence, padding_increase, reason.
    Returns {"still_present": False} on any failure (assume success).
    """
    prompt = _CLAUDE_VERIFY_PROMPT.format(
        image_path=str(Path(output_path).resolve()),
        object=object_name,
    )
    log.info(f"[verify] Asking claude to check if '{object_name}' is still present...")
    try:
        result = subprocess.run(
            [claude_bin, "-p", prompt],
            capture_output=True, text=True, timeout=60,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired) as e:
        log.warning(f"[verify] claude -p failed ({e}); assuming success.")
        return {"still_present": False}

    if result.returncode != 0:
        log.warning(f"[verify] claude -p exited {result.returncode}; assuming success.")
        return {"still_present": False}

    stdout = result.stdout.strip()
    log.info(f"[verify] Claude response: {stdout}")

    data = _extract_last_json(stdout)  # last block: Claude sometimes self-corrects in a second block
    if not data:
        log.warning("[verify] No JSON in claude response; assuming success.")
        return {"still_present": False}

    return data


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = build_parser()
    args   = parser.parse_args()

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    if args.mode in SHOULD_NOT_USE:
        log.error(f"[{args.mode}] SHOULD NOT USE: {SHOULD_NOT_USE[args.mode]}")
        sys.exit(2)

    engine_tag = f" | engine={args.engine}" if args.mode == "inpaint" else ""
    log.info(f"Mode: {args.mode}{engine_tag} | Device: {args.device} | FP16: {not args.no_fp16}")
    log.info(f"VRAM profile: {cfg.VRAM_PROFILES[args.mode]}")

    pipe = load_pipe_for_mode(args.mode, args)

    try:
        if args.manifest:
            # Batch mode: resolve mask once then run all items
            if args.mode == "inpaint":
                resolve_mask_and_prompt(args)
            _validate_args(args.mode, args)
            run_batch(args.mode, pipe, args)

        elif args.mode == "inpaint" and not args.manifest:
            # Single inpaint with optional auto-verify + retry loop.
            # Save original object name so mask can be regenerated on retry.
            _orig_mask        = args.mask          # may be object name or file path
            _is_auto_mask     = _orig_mask and not Path(_orig_mask).exists()
            _max_retries      = getattr(args, "max_retries", 3)
            _verify_enabled   = _is_auto_mask and _max_retries > 0

            resolve_mask_and_prompt(args)
            _validate_args(args.mode, args)
            run_single(args.mode, pipe, args)

            if _verify_enabled:
                out_path    = args.output or _default_output(args, args.mode)
                object_name = _orig_mask
                claude_bin  = getattr(args, "claude_bin", "claude")

                for attempt in range(1, _max_retries + 1):
                    v = verify_inpaint(out_path, object_name, claude_bin)

                    if not v.get("still_present", False):
                        log.info(
                            f"[verify] '{object_name}' not detected — inpaint accepted "
                            f"(confidence={v.get('confidence', '?')})."
                        )
                        break

                    # Object still visible — increase padding and retry
                    increase = max(int(v.get("padding_increase", 50)), 20)
                    log.warning(
                        f"[verify] Attempt {attempt}/{_max_retries}: '{object_name}' still present "
                        f"({v.get('reason', '')}).  "
                        f"Increasing mask_padding by {increase}px and retrying..."
                    )
                    args.mask         = object_name          # restore for re-generation
                    args.mask_padding = getattr(args, "mask_padding", 100) + increase

                    # Delete old mask file so it is regenerated with new padding
                    old_mask_path = Path(args.input).parent / \
                        f"{Path(args.input).stem}_mask_{object_name.replace(' ', '_')}.png"
                    if old_mask_path.exists():
                        old_mask_path.unlink()

                    resolve_mask_and_prompt(args)
                    run_single(args.mode, pipe, args)
                else:
                    log.warning(
                        f"[verify] Max retries ({_max_retries}) reached. "
                        "Keeping last result. Consider running with --mask-padding manually."
                    )

        else:
            _validate_args(args.mode, args)
            run_single(args.mode, pipe, args)

    finally:
        unload_pipe(pipe)
        log.info("Pipeline complete.")


if __name__ == "__main__":
    main()
