# =============================================================================
# placeholder_for_lipsync.py
# Documents the GPU requirements for running gen_lipsync.py with the
# originally specified LatentSync 1.5 model (ByteDance).
#
# This script does NOT generate any assets. Run it to see what GPU is
# needed and what the upgrade path looks like.
# =============================================================================

import sys

def main():
    print()
    print("=" * 70)
    print("BLOCKED: LatentSync 1.5 — Cannot reliably run on RTX 4060 8 GB")
    print("=" * 70)
    print()
    print("Model:   ByteDance/LatentSync-1.5")
    print("Type:    Latent diffusion UNet for lip-sync")
    print()
    print("VRAM breakdown:")
    print("  UNet weights (FP16):              ~4-6 GB")
    print("  Whisper audio encoder (FP16):     ~1-2 GB")
    print("  Face detection + preprocessing:   ~1 GB")
    print("  Denoising forward pass activations: ~6-8 GB peak")
    print("  Total peak during denoising loop: ~14-16 GB")
    print()
    print("WHY IT OOMs:")
    print("  LatentSync runs a full diffusion denoising loop (20 steps) over")
    print("  a face-region latent conditioned on Whisper audio features.")
    print("  The UNet activations during each forward pass peak at ~6-8 GB,")
    print("  which combined with weights and preprocessing exhausts 8 GB.")
    print("  CPU offload helps but the denoising pass itself still OOMs.")
    print()
    print("─" * 70)
    print("CURRENT 8 GB FALLBACK (active in gen_lipsync.py):")
    print("─" * 70)
    print()
    print("  Model:   Wav2Lip / Wav2Lip-GAN")
    print("  VRAM:    ~500 MB (runs on any GPU or CPU)")
    print("  Quality: Classic GAN quality — less photorealistic than LatentSync")
    print("           but fully functional for prototype purposes.")
    print()
    print("  Setup:")
    print("    git clone https://github.com/Rudrabha/Wav2Lip")
    print("    # Download wav2lip_gan.pth — see Wav2Lip repo README for link")
    print("    # Place at: Wav2Lip/checkpoints/wav2lip_gan.pth")
    print("    pip install -r Wav2Lip/requirements.txt")
    print("    python gen_lipsync.py --wav2lip_dir Wav2Lip")
    print()
    print("─" * 70)
    print("GPU UPGRADE PATH:")
    print("─" * 70)
    print()
    print("  GPU             VRAM   Unlocks")
    print("  ─────────────── ────── ──────────────────────────────────────────")
    print("  RTX 4060 8 GB   8 GB   Wav2Lip only (current)")
    print("  RTX 4080 16 GB  16 GB  LatentSync 1.5 (FP16 + CPU offload)")
    print("  RTX 3090 24 GB  24 GB  LatentSync 1.5 full precision")
    print("  A100 40/80 GB   40 GB  LatentSync 1.5 + batch processing")
    print()
    print("─" * 70)
    print("INSTALL NOTES FOR LATENTSYNC (when you have the GPU):")
    print("─" * 70)
    print()
    print("  git clone https://github.com/bytedance/LatentSync")
    print("  huggingface-cli login   # accept licence at ByteDance/LatentSync-1.5")
    print("  huggingface-cli download ByteDance/LatentSync-1.5 \\")
    print("      --local-dir LatentSync/checkpoints/latentsync_1.5")
    print("  pip install -r LatentSync/requirements.txt")
    print()
    print("  Run inference:")
    print("    python LatentSync/inference.py \\")
    print("      --unet_config_path LatentSync/configs/unet/second_stage.yaml \\")
    print("      --inference_ckpt_path LatentSync/checkpoints/latentsync_1.5/latentsync_unet.pt \\")
    print("      --video_path input.mp4 \\")
    print("      --audio_path audio.wav \\")
    print("      --video_out_path output.mp4")
    print()
    print("  HuggingFace: https://huggingface.co/ByteDance/LatentSync-1.5")
    print("  GitHub:      https://github.com/bytedance/LatentSync")
    print()
    sys.exit(0)


if __name__ == "__main__":
    main()
