# =============================================================================
# placeholder_for_music_medium.py
# Documents the GPU requirements for running gen_music.py with
# MusicGen medium or large instead of the small variant.
#
# This script does NOT generate any assets. Run it to see what GPU is
# needed and what the quality difference looks like.
# =============================================================================

import sys

def main():
    print()
    print("=" * 70)
    print("QUALITY UPGRADE: MusicGen Medium / Large -- Needs 10-20 GB VRAM")
    print("=" * 70)
    print()
    print("Current (8 GB):  facebook/musicgen-small   (~4-6 GB VRAM,  300M params)")
    print("Upgrade target:  facebook/musicgen-medium  (~10-12 GB VRAM, 1.5B params)")
    print("Premium target:  facebook/musicgen-large   (~20+ GB VRAM,  3.3B params)")
    print()
    print("WHY MEDIUM/LARGE DON'T FIT ON 8 GB:")
    print()
    print("  MusicGen medium (1.5B params):")
    print("    Weights (FP32): ~6 GB")
    print("    KV-cache + activations during generation: ~4-6 GB")
    print("    Total peak: ~10-12 GB -- exceeds 8 GB budget")
    print()
    print("  MusicGen large (3.3B params):")
    print("    Weights (FP32): ~13 GB -- exceeds budget before activations")
    print("    Total peak: ~20+ GB")
    print()
    print("QUALITY DIFFERENCE:")
    print()
    print("  Small:  Captures basic mood and rhythm. Simple harmonic content.")
    print("          Adequate for prototype review and timeline placement.")
    print()
    print("  Medium: Richer orchestration, better instrument separation,")
    print("          more coherent long-form structure. Recommended for")
    print("          final pipeline output up to 16 GB VRAM.")
    print()
    print("  Large:  Most expressive, broadest harmonic vocabulary,")
    print("          best long-duration coherence. Requires 24 GB+.")
    print()
    print("-" * 70)
    print("GPU UPGRADE PATH:")
    print("-" * 70)
    print()
    print("  GPU             VRAM   MusicGen Model")
    print("  --------------- ------ ------------------------------------------")
    print("  RTX 4060 8 GB   8 GB   musicgen-small only (current)")
    print("  RTX 4080 16 GB  16 GB  musicgen-medium [ok]")
    print("  RTX 3090 24 GB  24 GB  musicgen-medium [ok] + musicgen-large (tight)")
    print("  RTX 4090 24 GB  24 GB  musicgen-large [ok] (FP16 helps here)")
    print("  A100 40/80 GB   40 GB  musicgen-large full precision + batching")
    print()
    print("-" * 70)
    print("HOW TO SWITCH TO MEDIUM (when you have the GPU):")
    print("-" * 70)
    print()
    print("  Option A -- use the --model flag:")
    print("    python gen_music.py --model medium")
    print()
    print("  Option B -- change the default in gen_music.py:")
    print("    parser.add_argument('--model', ... default='medium' ...)")
    print()
    print("  No other code changes needed -- gen_music.py already supports both.")
    print()
    print("-" * 70)
    print("HOW TO SWITCH TO LARGE (requires code change):")
    print("-" * 70)
    print()
    print("  Add 'large' to the choices in gen_music.py parse_args():")
    print("    choices=['small', 'medium', 'large']")
    print()
    print("  Add the model ID mapping in load_musicgen():")
    print("    MUSICGEN_LARGE = 'facebook/musicgen-large'")
    print("    model_id = {'small': MUSICGEN_SMALL,")
    print("                'medium': MUSICGEN_MEDIUM,")
    print("                'large': MUSICGEN_LARGE}[size]")
    print()
    sys.exit(0)


if __name__ == "__main__":
    main()
